INSERT INTO devices (name, model_name, serial_number, status) VALUES ('PET/CT Scanner', 'Biograph Vision', 'SN-005', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Angiography System', 'Artis pheno', 'SN-006', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Mammography System', 'MAMMOMAT Revelation', 'SN-007', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Mobile C-Arm', 'Cios Spin', 'SN-008', 'MAINTENANCE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Patient Monitor', 'IntelliVue MX800', 'SN-009', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Ventilator', 'Hamilton-G5', 'SN-010', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Anesthesia Machine', 'Avance CS2', 'SN-011', 'OFFLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Infusion Pump', 'Alaris Plus', 'SN-012', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Defibrillator', 'LIFEPAK 15', 'SN-013', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Surgical Robot', 'Da Vinci Xi', 'SN-014', 'MAINTENANCE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Electrosurgical Unit', 'Ligasure ForceTriad', 'SN-015', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Surgical Microscope', 'ZEISS KINEVO 900', 'SN-016', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Endoscopy Tower', 'EVIS EXERA III', 'SN-017', 'OFFLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Blood Analyzer', 'Cobas 8000', 'SN-018', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('PCR Thermal Cycler', 'QuantStudio 7', 'SN-019', 'ONLINE');
INSERT INTO devices (name, model_name, serial_number, status) VALUES ('Centrifuge', 'Allegra X-30', 'SN-020', 'MAINTENANCE');